### ISSUE TITLE
postgres_mapper crate similarity

### ISSUE THREAD

**Issue by Dowwie** [1aim/serde_postgres#2]
Hi.  Did you miss this crate before you built what appears to be the equivalent?  https://github.com/zeyla/postgres-mapper

The author hasn't been too active but the crate works fine!

**Comment by Aaronepower** [comment]
Thank you for your issue! While I did not know about that crate they aren't exactly equivalent. `postgres-mapper` is a proc macro that generates a `From` implementation for the struct. `serde_postgres` leverages the existing `serde` framework to provide the deserialisation. `postgres-mapper`'s `From` implementation is also not our desired behaviour as that `From` implementation can panic, and we intend to use this in production servers. There is also features I intend to support such as tuple structs that are not supported in `postgres-mapper`.

**Comment by Dowwie** [comment]
@Aaronepower  postgres_mapper's ``from_postgres_row`` does *not* panic, where as the other ``from`` feature does.  Further, in order to use serde_postgres, every field type must implement Deserialize where as with postgres_mapper, this is not so.   Think:  Interval, Array, TSTZRange, etc
